[package]
name = "time_priority_order_algoritmh"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
exclude = [
    ".gitignore",
    ".vscode/*"
]

[dependencies]
sortedlist-rs = { version = "0.2.3"}

[dev-dependencies]
rand = "0.8.5"
chrono = "0.4.39"
